name: Deploy Flutter Web to GitHub Pages

# Grant write access so the job can push to gh-pages
permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # don’t reuse the default token
          fetch-depth: 0              # fetch full history

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build web
        run: flutter build web --release --base-href /Personal-Portfolio-Flutter/

      - name: Deploy to gh-pages
        env:
          GH_PAGES_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          set -eux

          # Navigate to the built output
          cd build/web

          # Initialize a new Git repo with 'main' as the default branch
          git init -b main
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Add and commit all files
          git add --all
          git commit -m "Deploy from $GITHUB_SHA"

          # Push the 'main' branch to 'gh-pages'
          git push --force \
            "https://${GITHUB_ACTOR}:${GH_PAGES_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" \
            main:gh-pages
