name: Deploy Flutter Web to GitHub Pages

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build web
        run: flutter build web --release

      - name: Deploy to gh-pages
        env:
          GH_PAGES_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
        run: |
          set -eux

          # 1. Enter build output
          cd build/web

          # 2. Init a fresh Git repo
          git init
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # 3. Commit everything
          git add --all
          git commit -m "Deploy from $GITHUB_SHA"

          # 4. Push to gh-pages using actor as user and PAT as password
          git push --force \
            "https://${GITHUB_ACTOR}:${GH_PAGES_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" \
            HEAD:gh-pages
