name: Deploy Flutter Web to GitHub Pages

# Grant write access so we can push to gh-pages
permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Don’t reuse the default token, and fetch full history
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build web
        run: flutter build web --release

      - name: Deploy to GitHub Pages
        env:
          GH_PAGES_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
        run: |
          set -eux

          # 1. Enter the build output
          cd build/web

          # 2. Initialize a fresh Git repo
          git init
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # 3. Commit all files
          git add --all
          git commit -m "Deploy from $GITHUB_SHA"

          # 4. Push to gh-pages (force update)
          git push --force "https://${GH_PAGES_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" HEAD:gh-pages
